### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by richyrb00** [valor-software/ng2-contentful#4]
am i right in saying that this repo doesn't work on installing node packages? 

fails on a few things. 

node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v46-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@4.2.6 (node-v46 ABI) (falling back to source compile with node-gyp) 

----
also 

error TS6053: File 'typings/browser.d.ts' not found.

**Comment by valorkin** [comment]
zopli is common problem of webpack compress plugin 
if download fails it will try to build it locally,
see https://www.npmjs.com/package/node-gyp#installation
you need to configure this tool

to have typings, you need to install them with typings (until TS 2 or 1.9)
see https://www.npmjs.com/package/typings for more info
